# Generated by Django 4.1.3 on 2022-11-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_name', models.CharField(max_length=200)),
                ('photos', models.ImageField(upload_to='')),
            ],
        ),
    ]
