# Generated by Django 4.1.3 on 2022-11-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Storage',
            new_name='Photos',
        ),
    ]
