# Generated by Django 4.1.3 on 2022-11-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_rename_storage_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='photos',
            new_name='photos_file',
        ),
    ]
