# Generated by Django 4.1.3 on 2022-11-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_rename_photos_photos_photos_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='photos_file',
            new_name='photo_file',
        ),
    ]
