# Generated by Django 4.1.3 on 2022-11-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_rename_photos_file_photos_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo_file',
            field=models.BinaryField(),
        ),
    ]
