# Generated by Django 4.1.3 on 2022-11-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('storage', '0005_alter_photos_photo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo_file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
