# Generated by Django 4.1.3 on 2022-11-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_remove_photos_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo_file',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
