# Generated by Django 4.1.3 on 2022-11-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_photos_user_id_alter_photos_photo_file'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SystemUser',
        ),
    ]
