# Generated by Django 4.1.3 on 2022-11-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_name_systemuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='auth_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
