# Generated by Django 4.1.3 on 2022-11-28 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_remove_photos_user_id'),
        ('authentication', '0005_alter_systemuser_auth_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemUser',
        ),
    ]
